# Generated by Django 6.0.5 on 2026-07-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_scoringrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoringRequest',
        ),
    ]
