# Generated by Django 6.0.5 on 2026-08-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_scoringrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('tester', 'Tester')], default='user', max_length=10),
        ),
    ]
