# Generated by Django 6.0.5 on 2026-08-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'Scorer'), ('tester', 'Tester')], default='user', max_length=10),
        ),
    ]
