# Generated by Django 6.0.5 on 2026-08-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('scorer', 'Scorer'), ('tester', 'Tester')], default='', max_length=10),
        ),
    ]
