# Generated by Django 6.0.5 on 2026-07-18 12:44

import annotation.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(choices=[('FRONT1', 'Front 1'), ('FRONT2', 'Front 2'), ('SIDE', 'Side')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('record_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_zip', models.CharField(blank=True, max_length=255, null=True)),
                ('target_type', models.CharField(choices=[('FRONT_PAIR_F1', 'Front Pair F1'), ('FRONT_PAIR_F2', 'Front Pair F2'), ('FRONT_PAIR_B1', 'Front Pair B1'), ('FRONT_PAIR_B2', 'Front Pair B2'), ('SIDE_F1', 'Side F1'), ('SIDE_F2', 'Side F2'), ('SIDE_B1', 'Side B1'), ('SIDE_B2', 'Side B2'), ('FRONT_F1', 'Front F1'), ('FRONT_F2', 'Front F2'), ('FRONT_B1', 'Front B1'), ('FRONT_B2', 'Front B2')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='cow_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cows', to='annotation.farm')),
            ],
            options={
                'unique_together': {('farm', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.PositiveIntegerField()),
                ('image', models.ImageField(max_length=255, upload_to=annotation.models.Frame.original_path)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='annotation.cameraview')),
            ],
            options={
                'ordering': ['frame_number'],
                'unique_together': {('view', 'frame_number')},
            },
        ),
        migrations.CreateModel(
            name='ImportedJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='json_files', to='annotation.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FrameAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoof_label', models.CharField(max_length=2)),
                ('x1', models.PositiveIntegerField()),
                ('y1', models.PositiveIntegerField()),
                ('x2', models.PositiveIntegerField()),
                ('y2', models.PositiveIntegerField()),
                ('cropped_image', models.ImageField(max_length=255, upload_to=annotation.models.FrameAnnotation.cropped_path)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotation.frame')),
                ('rating_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotation.ratingtarget')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_setup', models.CharField(choices=[('2', 'Two Cameras'), ('3', 'Three Cameras')], max_length=1)),
                ('total_frames', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='annotation.cow')),
            ],
        ),
        migrations.AddField(
            model_name='ratingtarget',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_targets', to='annotation.sequence'),
        ),
        migrations.AddField(
            model_name='cameraview',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='annotation.sequence'),
        ),
        migrations.AlterUniqueTogether(
            name='ratingtarget',
            unique_together={('sequence', 'target_type')},
        ),
        migrations.AlterUniqueTogether(
            name='cameraview',
            unique_together={('sequence', 'camera')},
        ),
        migrations.CreateModel(
            name='SequenceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(0, 'No Opinion'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='annotation.ratingtarget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'rating_target')},
            },
        ),
    ]
