# Generated by Django 6.0.5 on 2026-07-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_alter_sequencerating_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencerating',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Opinion'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')]),
        ),
    ]
